micronaut:
  application:
    name: casaDoCodigoKotlin

datasources:
  default:
    url: jdbc:mysql://127.0.0.1:3306/cdc_micronaut
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    schema-generate: CREATE_DROP
    dialect: H2

    driverClassName: com.mysql.jdbc.Driver
      username: admin
      password: qwerzxcv123
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      url: jdbc:mysql://192.168.1.121:3306/student